### ISSUE TITLE
Model gcode files

### ISSUE THREAD

**Issue by Protocol-X** [bigtreetech/BIQU-BX#10]
All of the models appear to be in a hex type format.   Please provide the correctformat.   You have provided us start and end code to set up these printers and there is no way to extract it from these files.  Trying to convert them to ascii just results in gibberish.

**Comment by thisiskeithb** [comment]
The `.gcode` files have image preview data embedded so you have to scroll below that.

Example: For the current [3DBenchy.gcode](https://github.com/bigtreetech/BIQU-BX/blob/5c7d32e474446e1a88884869bf2cec28986cf9e2/TF%20card%20data/Models/3DBenchy.gcode), the Simplify3D gcode starts around 593:

![image](https://user-images.githubusercontent.com/13375512/114315351-78b6c700-9ab3-11eb-9c04-5bc9149f4c76.png)

**Comment by Protocol-X** [comment]
Thank you for the information Keith

**Comment by Protocol-X** [comment]
User error.
