### ISSUE TITLE
Head crashing on homing Z

### ISSUE THREAD

**Issue by exxosuk** [bigtreetech/BIQU-BX#15]
I found part of this the problem with the Z- switch being unreliable. I have since changed it for a Hall effect switch which has greatly improved part of the problem.

However, there seems to be some scenarios where the Z axis is already homed, and when you manually home with G28, the head will continue to move towards the bed bending the mechanism upwards!

This does not always seem to happen. But there needs to be something in the software where homing the axis always moves Z axis upwards by something like 2mm first. Currently if it is already in the home position, and you home, it moves downwards crashing into the bed.

Currently homing seems to move the head downwards until switch is pressed. Its fair enough, but if the switch is already pressed it continues to move downwards causes the bed crash issue. Then the head will move upwards and slowly moved down again this time it will home correctly. Trying to manually move the z-axis downwards results in no movement as expected.

So there is clearly something wrong with the firmware. The homing Z axis should always move upwards until the switches released. Not move downwards straight away because if the switch is already closed it will cause the bed crash.

**Comment by Redam-Desiagn** [comment]
I found that adjusting the Z-switch a bit to get nozzle not crashing into bed helps but this is quite fiddly to get right.
